@TeamService.API_HostAddress = http://localhost:5193

GET {{TeamService.API_HostAddress}}/weatherforecast/
Accept: application/json

###

@MatchService.API_HostAddress = http://localhost:5237

### Get completed match
GET {{MatchService.API_HostAddress}}/api/matches/completed/1
Accept: application/json
